name: "Test: Run in sequence"

on:
  push:
    branches:
      - main

jobs:
  one:
    paths:
      - one/**
    name: "Run when there are changes to One"
    steps:
      - name: "Echo One"
        run: echo 'One runs'
