name: Conditional Job Dependencies

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.changed_files, 'one/**') }} # Condition for job1 based on changes to path1
    steps:
      - name: Job 1
        run: echo "This is job 1, triggered by changes to one/**."

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ always() && needs.job1.result != 'running' && contains(github.event.changed_files, 'two/**') }}
    steps:
    steps:
      - name: Job 2
        run: echo "This is job 2, triggered by changes to path 'two/**' and when job1 is skipped, failed, or cancelled."

  job3:
    needs: job2
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.changed_files, 'three/**') }} # Condition for job3 based on changes to path3
    steps:
      - name: Job 3
        run: echo "This is job 3, triggered by changes to three/**."
