name: Folder Changes Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.files, 'one/') }}
    steps:
      - name: Job 1
        run: echo "This is job 1. Changes detected in folder 'one'."

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.files, 'two/**') && needs.job1.result != 'running' }}
    steps:
      - name: Job 2
        run: echo "This is job 2. Changes detected in folder 'two' after 'job1' is not running."

  job3:
    needs: [job1, job2]
    runs-on: ubuntu-latest
    if: ${{ (needs.job1.result != 'skipped' && needs.job2.result != 'skipped') && (!contains(github.event.inputs.files, 'one/') || !contains(github.event.inputs.files, 'two/')) && contains(github.event.inputs.files, 'three/') }}
    steps:
      - name: Job 3
        run: echo "This is job 3. Changes detected in folder 'three' after 'job1' and 'job2' completed."
