name: Conditional Job Dependencies

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.files, '**/one.md') }}
    steps:
      - name: Job 1
        run: echo "This is job 1, triggered by changes to one.md."

  job2:
    needs: job1
    runs-on: ubuntu-latest
    if: ${{ needs.job1.result != 'running' && contains(github.event.inputs.files, '**/two.md') }}
    steps:
      - name: Job 2
        run: echo "This is job 2, triggered by changes to two.md and job1 is not running."

  job3:
    needs: job2
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.inputs.files, '**/three.md') }}
    steps:
      - name: Job 3
        run: echo "This is job 3, triggered by changes to three.md."
